name: Deploy Hugo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build Hugo
        run: hugo

      - name: Deploy Hugo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.challengehub }} # 这里的 ACTIONS_DEPLOY_KEY 则是上面设置 Private Key的变量名
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
          cname: challengehub.cn
          commit_message: ${{ github.event.head_commit.message }}